name: Install swift-format
description: Installs swift-format in standard paths on the system

inputs:
  ref:
    description: "The version of swift-format you wish to install."
    required: true  

runs:
  using: 'composite'

  steps:
    - name: Clone swift-format
      uses: actions/checkout@v3
      with:
        repository: apple/swift-format
        ref: ${{ inputs.ref }}  
        path: swift-format

    - name: Install swift-format
      if: ${{ runner.os == 'Linux' }}
      run: |
        cp swift-format
        swift build -c release
        install .build/release/swift-format /usr/local/bin/
        install .build/release/*.so* /usr/local/lib/
      shell: bash

    - name: Install swift-format
      if: ${{ runner.os == 'macOS' }}
      run: |
        cp swift-format
        swift build -c release
        install .build/release/swift-format /usr/local/bin/
        install .build/release/*.dylib* /usr/local/lib/
      shell: bash

    - name: Add Environment Variables
      if: ${{ runner.os == 'Linux' || runner.os == 'macOS' }}
      run: |
        export PKG_CONFIG_PATH="/usr/local/lib/pkgConfig:$PKG_CONFIG_PATH"
        export LIB="/usr/local/lib:$LIB"
        export LIBPATH="/usr/local/lib:$LIBPATH"
        export LIBRARY_PATH="/usr/local/lib:$LIBRARY_PATH"
        export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
        export INCLUDE="/usr/local/include:$INCLUDE"
        export IFCPATH="/usr/local/include:$IFCPATH"
        export CPATH="/usr/local/include:$CPATH"
        echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH" >> $GITHUB_ENV
        echo "INCLUDE=$INCLUDE" >> $GITHUB_ENV
        echo "CPATH=$CPATH" >> $GITHUB_ENV
        echo "IFCPATH=$IFCPATH" >> $GITHUB_ENV
        echo "LIB=$LIB" >> $GITHUB_ENV
        echo "LIBPATH=$LIBPATH" >> $GITHUB_ENV
        echo "LIBRARY_PATH=$LIBRARY_PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> $GITHUB_ENV
      shell: bash
